apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: app
  annotations:
    azure.workload.identity/client-id: "REPLACE_WITH_MANAGED_IDENTITY_CLIENT_ID"
automountServiceAccountToken: false
